apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-name-mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1  # Number of MongoDB instances (pods)
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest  # MongoDB image
          ports:
            - containerPort: 27017  # MongoDB default port
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password