apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-file-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

